### ISSUE TITLE
GPU Miner

### ISSUE THREAD

**Issue by dongqn** [ProgrammerDan/arionum-java#13]
hello,
plz sp miner GPU

**Comment by tinkermade** [comment]
If you’re asking for a GPU miner for $ARO, you’re missing the point entirely.  CPU-only coins democratize access for anyone with a computer to participate in mining.

**Comment by ProgrammerDan** [comment]
I had initially thought about porting a "best effort" GPU miner into this wrapper, but I don't think I will continue with that plan; other folks have done so, and I see no advantage to have it here.
