### ISSUE TITLE
Ryzen 2 chip hashrate issue

### ISSUE THREAD

**Issue by pricejn2** [ProgrammerDan/arionum-java#15]
I was running your miner on a Ryzen 1st gen processor for a bit and didn't have any issues. Just tested on a Ryzen 2nd gen processor (the 2600) and H/s starts at expected levels -- roughly 2 H/s/hasher. However, after a few cycles, it drops down to a total 6-7 H/s. In the case of the 2600 I tested (a 6c/12t processor), using 2 hashers is the only stable value where initial H/s = longer-term H/s. Any ideas what could be going on?

**Comment by ProgrammerDan** [comment]
Hmm, hard to say in the blind. Nothing in the miner itself should cause issues, but a few thoughts:

1) Check for other running processes, things like antivirus's I've heard occasionally start ramping up

2) Memory fragmentation. Consider for your operating system turning on hugepages. Memory bandwidth is most critical, and pages of memory are allocated in 512mb blocks -- the more fragmented, the slower.

3) If you haven't, upgrade to 0.2.5 -- there are changes in memory handling, allocation, cycling, and thread / core allocation longterm. If you're having these issues already with 0.2.5, for sure check the other notes.

4) Running any other miners, GPU miners? Could be CPU contention.

Generally, monitor other running tasks and see if there are signs of resource contention. If you get slowdown over time might be OS scheduling, memory fragmentation, contention... let me know what else you find, would love to improve my understanding of things that impact mining!

**Comment by pricejn2** [comment]
Thanks for the feedback! I ran all my tests on a clean windows install with nothing else running, ruling out most software interference. 

Here is a screenshot of what I'm seeing with 0.2.5. The slowdown is quick
![image](https://user-images.githubusercontent.com/1309479/41198065-b1e345aa-6c3d-11e8-8435-757435bc8a82.png)

I've tried the other two miners as well (avx and generic) and they produce similar results in terms of H/s drop off.

**Comment by ProgrammerDan** [comment]
OH! I thought you meant steady state dropoff. This kind of immediate dip is common.

Check your memory layout. Chances are good this new system has lower memory throughput, that seems to be the real problem then. Low memory throughput will have this outcome, and is often reported -- make sure your memory is using as many channels (generally via physical layout on the motherboard) as possible, and is low latency / high speed. Hope that helps!

Meant to also mention -- all systems I test on have this specific reporting outcome. I'm not 100% sure why, but some timer weirdness during initial startup causes the miner to over-report H/s for the first 5-10 seconds. I generally don't "sample" for h/s until the miner has been running for 5-10 minutes. At a bare minimum, let it run for 2 minutes, then check h/s for comparisons. Hope that helps!

**Comment by pricejn2** [comment]
Wow, good call! The RAM had come installed on the board wrong and was only running single-channel. Thanks a ton for the guidance!
